### PR TITLE
Carthage support - Created xcodeproj and share framework scheme

### PR DESCRIPTION
**Pull request by AndrewSB**

### CODE REVIEW

**Comment by AndrewSB** [comment]
Hey @wircho, not sure if this is the best way to create support, it may make sense to put the demo app into the workspace as another target.
Let me know what you think

**Comment by wircho** [comment]
Hi AndrewSB. I've been really busy so I haven't had time to take a look into this, and I don't know much about Carthage. I'll look into it as soon as I get some time. Thanks!

**Comment by AndrewSB** [comment]
sounds good @wircho :smile:

**Comment by AndrewSB** [comment]
hey @wircho, sure you're still busy, but would love to get this merged in so I can delete my fork :smile:

**Comment by AndrewSB** [comment]
hey @wircho, checking in again, would love to get this integrated!

**Comment by wircho** [comment]
I'll merge it now!

**Comment by AndrewSB** [comment]
🎉

**Pull request merged**
